using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Api.Data.CosmosDb.Models
{
    /// <summary>
    /// Implements auto generated Id property for CosmosDb Model
    /// </summary>
    public abstract class CosmosModelBase
    {
        /// <summary>
        /// PK for this model. (apart from the ResourceId which is internally generated by CosmoDb)
        /// If the user does not set this, the SDK will set this automatically.
        /// See: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.resource.id?view=azure-dotnet
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public virtual string Id { get; set; }

        /// <summary>
        /// Any unmapped properties from the JSON data deserializes into this property.
        /// See: https://www.jerriepelser.com/blog/using-jsonextensiondata-with-jsonnet/
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, JToken> UnmappedData { get; set; }

        public DateTime CreatedOnUtc { get; set; } = DateTime.UtcNow;
    }
}
