// <auto-generated />
namespace Api.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cosmos_CreateCosmosDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cosmos_CreateCosmosDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201901150915487_Cosmos_CreateCosmosDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
