// <auto-generated />
namespace Api.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cosmos_CreatePostsCollection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cosmos_CreatePostsCollection));
        
        string IMigrationMetadata.Id
        {
            get { return "201901151513458_Cosmos_CreatePostsCollection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
